let suggestions = [
    "من",
    "تو",
    "شما",
    "انها",
    "ان",
    "اون",
    "خدا",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
];
